version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: rab_test_cel_local_django
    container_name: rab_test_cel_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
      - '5678:5678'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: rab_test_cel_production_postgres
    container_name: rab_test_cel_local_postgres
    volumes:
      - rab_test_cel_local_postgres_data:/var/lib/postgresql/data
      - rab_test_cel_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  # docs:
  #   image: rab_test_cel_local_docs
  #   container_name: rab_test_cel_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./rab_test_cel:/app/rab_test_cel:z
  #   ports:
  #     - '9000:9000'
  #   command: /start-docs

  # redis:
  #   image: redis:6
  #   container_name: rab_test_cel_local_redis

  # celeryworker:
  #   <<: *django
  #   image: rab_test_cel_local_celeryworker
  #   container_name: rab_test_cel_local_celeryworker
  #   depends_on:
  #     - redis
  #     - postgres
  #     - rabbitmq
  #   ports: []
  #   command: /start-celeryworker

  # celerybeat:
  #   <<: *django
  #   image: rab_test_cel_local_celerybeat
  #   container_name: rab_test_cel_local_celerybeat
  #   depends_on:
  #     - redis
  #     - postgres
  #     - rabbitmq
  #   ports: []
  #   command: /start-celerybeat

  # flower:
  #   <<: *django
  #   image: rab_test_cel_local_flower
  #   container_name: rab_test_cel_local_flower
  #   ports:
  #     - '5555:5555'
  #   command: /start-flower
  
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - '5672:5672'
  #     - '15673:15672'
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq


volumes:
  rab_test_cel_local_postgres_data: {}
  rab_test_cel_local_postgres_data_backups: {}