# Generated by Django 4.2.3 on 2023-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnlineAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.TextField(help_text="The ID generate from rabbit mq.", verbose_name="Task ID")),
                (
                    "account_detail",
                    models.JSONField(
                        help_text="The json that include all the response.", verbose_name="Account Details"
                    ),
                ),
                ("status", models.BooleanField(default=False, help_text="The account status.", verbose_name="status")),
            ],
            options={
                "db_table": "online_account",
            },
        ),
    ]
